<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IMCHDT024" name="Default test" tests="26" failures="2" timestamp="26 Aug 2014 10:38:57 GMT" time="128.843" errors="0">
  <testcase name="username_verification_empty" time="2.543" classname="Tests.FiledValidation"/>
  <testcase name="username_verification_exist" time="2.908" classname="Tests.FiledValidation"/>
  <testcase name="username_verification_min" time="2.439" classname="Tests.FiledValidation"/>
  <testcase name="username_verification_max" time="2.524" classname="Tests.FiledValidation"/>
  <testcase name="username_verification_valid" time="2.567" classname="Tests.FiledValidation"/>
  <testcase name="email_verification_empty" time="2.249" classname="Tests.FiledValidation"/>
  <testcase name="email_verification_exist" time="3.36" classname="Tests.FiledValidation"/>
  <testcase name="email_verification_valid" time="2.278" classname="Tests.FiledValidation"/>
  <testcase name="email_verification_max" time="7.362" classname="Tests.FiledValidation"/>
  <testcase name="cemail_verification_empty" time="2.216" classname="Tests.FiledValidation"/>
  <testcase name="cemail_verification_max" time="7.304" classname="Tests.FiledValidation"/>
  <testcase name="firstname_verification_empty" time="2.316" classname="Tests.FiledValidation"/>
  <testcase name="firstname_verification_min" time="5.617" classname="Tests.FiledValidation"/>
  <testcase name="firstname_verification_invalid" time="2.394" classname="Tests.FiledValidation"/>
  <testcase name="firstname_verification_max" time="6.714" classname="Tests.FiledValidation"/>
  <testcase name="lastname_verification_empty" time="2.269" classname="Tests.FiledValidation"/>
  <testcase name="lastname_verification_min" time="5.697" classname="Tests.FiledValidation"/>
  <testcase name="lastname_verification_invalid" time="2.314" classname="Tests.FiledValidation"/>
  <testcase name="lastname_verification_max" time="6.729" classname="Tests.FiledValidation"/>
  <testcase name="address1_verification_empty" time="2.368" classname="Tests.FiledValidation"/>
  <testcase name="address1_verification_min" time="5.725" classname="Tests.FiledValidation"/>
  <testcase name="address1_verification_max" time="7.377" classname="Tests.FiledValidation"/>
  <testcase name="address2_verification_max" time="7.453" classname="Tests.FiledValidation"/>
  <testcase name="city_verification_empty" time="2.343" classname="Tests.FiledValidation"/>
  <testcase name="city_verification_min" time="5.778" classname="Tests.FiledValidation">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:192)
	at Tests.FiledValidation.city_verification_min(FiledValidation.java:441)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- city_verification_min -->
  <testcase name="city_verification_max" time="3.439" classname="Tests.FiledValidation">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;&amp;gt; but was:&amp;lt;City may not exceed 128 characters&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<City may not exceed 128 characters>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at Tests.FiledValidation.city_verification_max(FiledValidation.java:456)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- city_verification_max -->
</testsuite> <!-- Default test -->
